### PR TITLE
Add option to create target grid at runtime by parameter specification

### PR DESCRIPTION
**Pull request by LarissaReames-NOAA**
Users can now create a target grid on the fly, including global grids, instead of being forced to provide a WRF file target grid. 

I've tested Lambert conformal, regional lat-lon, and global lat-on configurations.

Also made I/O parallel netcdf friendly.

Made array creation cleaner and more MPI-friendly to reduce memory footprint.

@weather4evr If you have time, it would be great if you could test the new grid capabilities to flesh out anything that I've missed or might need to add/consider.

### CODE REVIEW

**Comment by weather4evr** [comment]
@LarissaReames-NOAA I'll try to test this out next week.

**Comment by LarissaReames-NOAA** [comment]
Bug fixes from @weather4evr have been implemented, along with some additional changes. You should now be able to run with the 'file' target type and use conservative regridding without issue.

**Comment by weather4evr** [comment]
I can now get identical results with conservative interpolation using this new branch for the 'file' target type.  Thank you for the fixes.

I then tried to manually define the grid contained in the file I had been using and was hoping to get the same answers from the user-defined grid and using the 'file' target type.  There were definitely differences.  In addition, the lat/lon arrays differed.  It's entirely possible I defined the grid incorrectly in the namelist.  Have you tried this test with the HRRR grid--both when using the file to define the grid and manually specifying it?

**Comment by LarissaReames-NOAA** [comment]
I have and I did notice some slight differences in the grid location when I put what I thought were HRRR-identical parameters in the namelist. I scavenged all of the internal code for creating the grid from WPS geogrid, so something may be slightly amiss in exactly how I pass the variables through compared to how it's done in geogrid.

**Comment by weather4evr** [comment]
Maybe it's due to the staggering?  In the WPS namelist, the nx/ny you input are number of staggered points.  In this code, it seems to be that what's input is the number of unstaggered points, as the output file has staggered dimensions of (nx+1, ny+1).

**Comment by LarissaReames-NOAA** [comment]
Yeah, that seems a likely culprit. I'll see if I can get it to use nx,ny as staggered points instead of center points.

**Comment by LarissaReames-NOAA** [comment]
Hmmmm. The grids are now the same size, but the old 'file' grid type looks to be about 1 grid point southwest of the 'Lambert' grid type 
(main) bash-4.2$  nccmp -dmfqS out_lcc_test.nc out_file_test.nc
Variable Group   Count          Sum      AbsSum          Min         Max       Range         Mean      StdDev
XLONG    /     1905141      32038.4     32038.4   0.00958252   0.0259666   0.0163841    0.0168168  0.00383956
XLONG_U  /     1906200      32054.9     32054.9   0.00957489   0.0259705   0.0163956    0.0168161  0.00384095
XLONG_V  /     1906940      32069.3     32069.3   0.00958252   0.0259743   0.0163918    0.0168172  0.00384075
XLAT     /     1905141        24951       24951   0.00710678   0.0174217   0.0103149    0.0130967  0.00257325
XLAT_U   /     1906200      24963.8     24963.8   0.00709915   0.0174217   0.0103226    0.0130961   0.0025746
XLAT_V   /     1906940      24974.1     24974.1   0.00710297   0.0174217   0.0103188    0.0130964   0.0025733
MAPFAC_M /     1902983     -7.05323     54.6037 -8.15392e-05 7.21216e-05 0.000153661 -3.70641e-06 3.36939e-05
MAPFAC_U /     1904056     -7.06653     54.6312 -8.16584e-05 7.21216e-05  0.00015378  -3.7113e-06 3.36921e-05
MAPFAC_V /     1904790     -7.05415     54.7063 -8.16584e-05 7.22408e-05 0.000153899 -3.70338e-06 3.37261e-05
HGT      /     1310925 -9.08217e+08 9.08266e+08     -3933.98     129.657     4063.64     -692.806     691.736
U10      /     1673529      358.494      285373     -8.58374     9.59716     18.1809  0.000214215     0.32892
T2       /     1620339      9247.27 1.10489e+06     -299.448      300.51     599.958     0.005707     11.5572

**Comment by weather4evr** [comment]
Not sure how you specified the lambert grid, but maybe you could specify the lat/lon of the SW corner and then use
ref_x = 1,
ref_y = 1?

That should at least force the SW corner points to be equal...I think.

**Pull request merged**
