### PR TITLE
Several changes and updates

### PR DESCRIPTION
**Pull request by ywangwof**
1. Trimmed some files with Fortran pretty formatter.

    You can compare the changes with the original files by ignoring white spaces with option `diff --ignore-space-change`.
    You can decide whether to accept this change or not.

2. Added/updated support on **Vecna** with **Intel classic suite and Openmpi**.
4. Merged with branch _**feature/vertex_var**_ for processing variable _vorticity_.
5. Added variable **_PB_** and some global attributes in the output file for directly processing it using **WoF-post**. Note that variable **P** will be all zeros and **PB** is the total pressure.

### CODE REVIEW

**Comment by LarissaReames-NOAA** [comment]
Can we separate out the actual changes from the formatting changes? I'm not opposed to making the formatting look nicer, it's just hard to track the actual changes in the file comparisons to see what's actually been changed in a substantial manner.

**Comment by ywangwof** [comment]
It will be easier to do comparison if you use option "ignore all white space" “diff -b”. You can also use xxdiff installed here, /home/yunheng.wang/bin/xxdiff <http://yunheng.wang/bin/xxdiff> and choose option “ignore white space”.

Yunheng.

**Comment by LarissaReames-NOAA** [comment]
So because I merged the previous PR (#8) that provided the grid-edge interpolation, your PR now has a ton of conflicts with all of the formatting changes that would be pretty hard to fix. Can you just pull out the actual code changes you made and submit those in a separate PR from the formatting changes? That's gonna be the easiest path forward and will make it easier to track what was changed when from the git log file.

**Comment by ywangwof** [comment]
Since we merged PR #11, this one is not necessary. So I will close it.

**Pull request closed without merging**
